# Site Settings
baseurl: ""
url : "https://ivanroldanannoson.github.io"

# Blog Settings
theme_settings :
  title : Ivan Roldan Annoson
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Ivan Roldan
    description : I am experienced Android Engineer with 5+ years working with Java & Kotlin with latest technology stack. Along with that I have worked on PHP, AWS, Azure and contributed my best on implementing features on project with Research.
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
      - skill : HTML5 & CSS
        value : 85  # Percent value
    education :
      - degree : BSC
        college : ICBT
      - degree : BSC
        college : ICBT
      - degree : BSC
        college : ICBT
    
        
  # Icons
  icons :
    email:  "ivanroldan@outlook.com" # Full email address, e.g. "sample@google.com"
    linkedin:  https://www.linkedin.com/in/ivanroldan # Full URL 
    github: ivanroldanannoson
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
