# Site Settings
baseurl: ""
url : "https://ivanroldanannoson.github.io"

# Blog Settings
theme_settings :
  title : Ivan Roldan Annoson
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Ivan Roldan Annoson
    designation : Software Engineer
    languages : Flutter, Kotlin, Java, PHP
    description : As a Mobile Software Engineer with over 5 years of experience, I have specialized in developing cutting-edge Android applications using the latest technology stack, including Java and Kotlin. I possess a strong knowledge of software engineering principles and have a proven track record of delivering high-quality, reliable code to meet project objectives. <br><br>In addition to my Android expertise, I have experience with PHP, AWS, and Azure, allowing me to integrate various systems and services seamlessly. I am passionate about staying up-to-date with the latest trends and developments in the mobile software industry, and I have contributed to various research initiatives to enhance project capabilities and optimize user experiences.
    experience :
      - start : 2022-Jun
        end : Present
        experience : Starhub Ltd. Singapore, Software Engineer
        responsibilites : <li>Develop and maintain multiple ongoing mobile projects using Kotlin, Flutter, and Java, ensuring that they meet project requirements and quality standards.</li>
          <li>Collaborate with cross-functional teams to align on project goals and timelines, and adapt to changes and client feedback to continuously improve project outcomes.</li>
          <li>Design and develop a Flutter web dashboard, leveraging expertise in web design principles and Flutter best practices.</li>
          <li>Utilize Strapi to develop and customize backend APIs, ensuring seamless integration with the mobile applications and meeting project-specific requirements.</li>
      - start : 2020-Jan
        end : 2022-May
        experience : InEight Sri Lanka, Software Engineer
        responsibilites :  <li>Develop, test, and implement application features using Kotlin, ensuring that they meet business requirements and quality standards.</li>
          <li>Collaborate with experienced team members to conduct root cause analysis of issues, review new and existing code, and continuously improve code quality.</li>
          <li>Work closely with core technology teams and other platform teams to balance cross-platform consistency with Android optimization, ensuring that the application performs optimally on Android devices.</li>
          <li>Customize the Foxit PDF viewer SDK to match business requirements, leveraging expertise in SDK customization and PDF viewer functionality.</li>
          <li>Design screens that are supported on both phone and tablet devices, using design best practices and responsive design principles.</li>
          <li>Maintain code standards and review the code of team members, ensuring that all code adheres to project guidelines and best practices.</li>
      - start : 2019-Aug
        end : 2020-Jan
        experience : Auxenta (PVT) Ltd., Software Engineer
        responsibilites :  <li>Modifying existing taxi hailing application for a corporate company transportation solution</li>
          <li>Worked with RxJava, Open Street map SDK and notifications</li>
          <li>Communicating between two applications (Driver – Passenger) Realtime with Web Sockets.</li>
      - start : 2017-Sep
        end : 2019-Jul
        experience : Capital Trust Securities (Acquired Airport Travels Holdings (Pvt) Ltd.), Software Engineer
        responsibilites :  <li>Passenger and Driver taxi hailing application development, managing</li>
          <li>Java, Rest API, Socket.io, Firebase database, Firebase notification technologies were used.</li>
          <li>Finding solution to match nearby drivers, animation of moving vehicles with real-time updates in firebase database.</li>
      - start : 2017-Apr
        end : 2017-Aug
        experience : Airport Travels Holdings (Pvt) Ltd, Associate Software Engineer
        responsibilites :  <li>Designing UI according to the business plan of Passenger and Driver application</li>
          <li>Implementing basic functionality of both applications</li>
          <li>Implementing cross platform communication with iOS application Passenger application through the Socket.IO technology</li>
    skills : 
      - skill : Koltin
        value : 85  # Percent value
      - skill : Java
        value : 90  # Percent value
      - skill : Flutter
        value : 60  # Percent value
      - skill : Corotine
        value : 755  # Percent value
      - skill : AWS
        value : 55  # Percent value
      - skill : Android studio
        value : 95  # Percent value
      - skill : Version control
        value : 85  # Percent value
      - skill : Firebase
        value : 90  # Percent value
      - skill : Azure
        value : 60  # Percent value
    education :
      - degree : Master of Science in Information Technology
        college : Cardiff Metropolitan University
      - degree : BSc (Hons) Software Engineering (First class)
        college : Cardiff Metropolitan University
      - degree : HND in Software Engineering and Computing
        college : ICBT Sri Lanka
      - degree : Diploma in Software Engineering
        college : Esoft Sri Lanka
      - degree : Training Course on Java Application Development using JavaSE
        college : University of Colombo School of Computing (UCSC)
      - degree : Diploma in Hardware Engineering with Networking
        college : Turnkey, Colombo-3
      - degree : Diploma in Windows Network Administration
        college : Turnkey, Colombo-3
      - degree : Certificate in Web Development using PHP
        college : Turnkey, Colombo-3
    
        
  # Icons
  icons :
    email:  "ivanroldan@outlook.com" # Full email address, e.g. "sample@google.com"
    linkedin:  https://www.linkedin.com/in/ivanroldan # Full URL 
    github: ivanroldanannoson
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
