# Site Settings
baseurl: ""
url : "https://ivanroldanannoson.github.io"

# Blog Settings
theme_settings :
  title : Ivan Roldan Annoson
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Ivan Roldan Annoson
    description : I am experienced Android Engineer with 5+ years working with Java & Kotlin with latest technology stack. Along with that I have worked on PHP, AWS, Azure and contributed my best on implementing features on project with Research.
    experience :
      - start : 2022-Jun
        end : Present
        experience : Starhub Ltd. Singapore, Software Engineer
        responsibilites : 
        - "Respons 1"
        - "Respons 2"
        - "Respons 3"
      - start : 2020-Jan
        end : 2022-May
        experience : InEight Sri Lanka, Software Engineer
      - start : 2019-Aug
        end : 2020-Jan
        experience : Auxenta (PVT) Ltd., Software Engineer
      - start : 2017-Sep
        end : 2019-Jul
        experience : Capital Trust Securities (Acquired Airport Travels Holdings (Pvt) Ltd.), Software Engineer
      - start : 2017-Apr
        end : 2017-Aug
        experience : Airport Travels Holdings (Pvt) Ltd, Associate Software Engineer
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
      - skill : HTML5 & CSS
        value : 85  # Percent value
    education :
      - degree : Master of Science in Information Technology
        college : Cardiff Metropolitan University
      - degree : BSc (Hons) Software Engineering (First class)
        college : Cardiff Metropolitan University
      - degree : HND in Software Engineering and Computing
        college : ICBT Sri Lanka
    
        
  # Icons
  icons :
    email:  "ivanroldan@outlook.com" # Full email address, e.g. "sample@google.com"
    linkedin:  https://www.linkedin.com/in/ivanroldan # Full URL 
    github: ivanroldanannoson
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
